# -*- coding: utf-8 -*-

from recc.variables.database import (
    INDEX_GROUP_SLUG,
    INDEX_PROJECT_SLUG,
    INDEX_ROLE_SLUG,
    INDEX_TASK_NAME,
    INDEX_USER_EMAIL,
    INDEX_USER_NAME,
    TABLE_GROUP,
    TABLE_PROJECT,
    TABLE_ROLE,
    TABLE_TASK,
    TABLE_USER,
)

CREATE_INDEX_USER_NAME = f"""
CREATE INDEX IF NOT EXISTS {INDEX_USER_NAME}
ON {TABLE_USER} (username);
"""

CREATE_INDEX_USER_EMAIL = f"""
CREATE INDEX IF NOT EXISTS {INDEX_USER_EMAIL}
ON {TABLE_USER} (email);
"""

CREATE_INDEX_GROUP_SLUG = f"""
CREATE INDEX IF NOT EXISTS {INDEX_GROUP_SLUG}
ON {TABLE_GROUP} (slug);
"""

CREATE_INDEX_ROLE_NAME = f"""
CREATE INDEX IF NOT EXISTS {INDEX_ROLE_SLUG}
ON {TABLE_ROLE} (name);
"""

CREATE_INDEX_PROJECT_NAME = f"""
CREATE INDEX IF NOT EXISTS {INDEX_PROJECT_SLUG}
ON {TABLE_PROJECT} (name);
"""

CREATE_INDEX_TASK_NAME = f"""
CREATE INDEX IF NOT EXISTS {INDEX_TASK_NAME}
ON {TABLE_TASK} (name);
"""

CREATE_INDICES = (
    CREATE_INDEX_USER_NAME,
    CREATE_INDEX_USER_EMAIL,
    CREATE_INDEX_GROUP_SLUG,
    CREATE_INDEX_ROLE_NAME,
    CREATE_INDEX_PROJECT_NAME,
    CREATE_INDEX_TASK_NAME,
)

DROP_INDEX_USER_NAME = f"DROP INDEX IF EXISTS {INDEX_USER_NAME};"
DROP_INDEX_USER_EMAIL = f"DROP INDEX IF EXISTS {INDEX_USER_EMAIL};"
DROP_INDEX_GROUP_NAME = f"DROP INDEX IF EXISTS {INDEX_GROUP_SLUG};"
DROP_INDEX_ROLE_NAME = f"DROP INDEX IF EXISTS {INDEX_ROLE_SLUG};"
DROP_INDEX_PROJECT_NAME = f"DROP INDEX IF EXISTS {INDEX_PROJECT_SLUG};"
DROP_INDEX_TASK_NAME = f"DROP INDEX IF EXISTS {INDEX_TASK_NAME};"

DROP_INDICES = (
    DROP_INDEX_USER_NAME,
    DROP_INDEX_USER_EMAIL,
    DROP_INDEX_GROUP_NAME,
    DROP_INDEX_ROLE_NAME,
    DROP_INDEX_PROJECT_NAME,
    DROP_INDEX_TASK_NAME,
)
