# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daemon.proto',
  package='recc.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x61\x65mon.proto\x12\nrecc.proto\"\x9e\x01\n\x07PacketQ\x12\x0e\n\x06method\x18\x01 \x01(\x05\x12\x31\n\x07headers\x18\x02 \x03(\x0b\x32 .recc.proto.PacketQ.HeadersEntry\x12\x14\n\x07\x63ontent\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_content\"\x9c\x01\n\x07PacketA\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x31\n\x07headers\x18\x02 \x03(\x0b\x32 .recc.proto.PacketA.HeadersEntry\x12\x14\n\x07\x63ontent\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_content2y\n\tDaemonApi\x12\x34\n\x06Packet\x12\x13.recc.proto.PacketQ\x1a\x13.recc.proto.PacketA\"\x00\x12\x36\n\x08Pickling\x12\x13.recc.proto.PacketQ\x1a\x13.recc.proto.PacketA\"\x00\x62\x06proto3'
)




_PACKETQ_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='recc.proto.PacketQ.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='recc.proto.PacketQ.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='recc.proto.PacketQ.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=175,
)

_PACKETQ = _descriptor.Descriptor(
  name='PacketQ',
  full_name='recc.proto.PacketQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='recc.proto.PacketQ.method', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='recc.proto.PacketQ.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='recc.proto.PacketQ.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PACKETQ_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='recc.proto.PacketQ._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=187,
)


_PACKETA_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='recc.proto.PacketA.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='recc.proto.PacketA.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='recc.proto.PacketA.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=175,
)

_PACKETA = _descriptor.Descriptor(
  name='PacketA',
  full_name='recc.proto.PacketA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='recc.proto.PacketA.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='recc.proto.PacketA.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='recc.proto.PacketA.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PACKETA_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='recc.proto.PacketA._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=190,
  serialized_end=346,
)

_PACKETQ_HEADERSENTRY.containing_type = _PACKETQ
_PACKETQ.fields_by_name['headers'].message_type = _PACKETQ_HEADERSENTRY
_PACKETQ.oneofs_by_name['_content'].fields.append(
  _PACKETQ.fields_by_name['content'])
_PACKETQ.fields_by_name['content'].containing_oneof = _PACKETQ.oneofs_by_name['_content']
_PACKETA_HEADERSENTRY.containing_type = _PACKETA
_PACKETA.fields_by_name['headers'].message_type = _PACKETA_HEADERSENTRY
_PACKETA.oneofs_by_name['_content'].fields.append(
  _PACKETA.fields_by_name['content'])
_PACKETA.fields_by_name['content'].containing_oneof = _PACKETA.oneofs_by_name['_content']
DESCRIPTOR.message_types_by_name['PacketQ'] = _PACKETQ
DESCRIPTOR.message_types_by_name['PacketA'] = _PACKETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketQ = _reflection.GeneratedProtocolMessageType('PacketQ', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _PACKETQ_HEADERSENTRY,
    '__module__' : 'daemon_pb2'
    # @@protoc_insertion_point(class_scope:recc.proto.PacketQ.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _PACKETQ,
  '__module__' : 'daemon_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.PacketQ)
  })
_sym_db.RegisterMessage(PacketQ)
_sym_db.RegisterMessage(PacketQ.HeadersEntry)

PacketA = _reflection.GeneratedProtocolMessageType('PacketA', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _PACKETA_HEADERSENTRY,
    '__module__' : 'daemon_pb2'
    # @@protoc_insertion_point(class_scope:recc.proto.PacketA.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _PACKETA,
  '__module__' : 'daemon_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.PacketA)
  })
_sym_db.RegisterMessage(PacketA)
_sym_db.RegisterMessage(PacketA.HeadersEntry)


_PACKETQ_HEADERSENTRY._options = None
_PACKETA_HEADERSENTRY._options = None

_DAEMONAPI = _descriptor.ServiceDescriptor(
  name='DaemonApi',
  full_name='recc.proto.DaemonApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=348,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='Packet',
    full_name='recc.proto.DaemonApi.Packet',
    index=0,
    containing_service=None,
    input_type=_PACKETQ,
    output_type=_PACKETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Pickling',
    full_name='recc.proto.DaemonApi.Pickling',
    index=1,
    containing_service=None,
    input_type=_PACKETQ,
    output_type=_PACKETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAEMONAPI)

DESCRIPTOR.services_by_name['DaemonApi'] = _DAEMONAPI

# @@protoc_insertion_point(module_scope)
