# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recc.proto.daemon_pb2 as daemon__pb2


class DaemonApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Packet = channel.unary_unary(
                '/recc.proto.DaemonApi/Packet',
                request_serializer=daemon__pb2.PacketQ.SerializeToString,
                response_deserializer=daemon__pb2.PacketA.FromString,
                )
        self.Pickling = channel.unary_unary(
                '/recc.proto.DaemonApi/Pickling',
                request_serializer=daemon__pb2.PacketQ.SerializeToString,
                response_deserializer=daemon__pb2.PacketA.FromString,
                )


class DaemonApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Packet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pickling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Packet': grpc.unary_unary_rpc_method_handler(
                    servicer.Packet,
                    request_deserializer=daemon__pb2.PacketQ.FromString,
                    response_serializer=daemon__pb2.PacketA.SerializeToString,
            ),
            'Pickling': grpc.unary_unary_rpc_method_handler(
                    servicer.Pickling,
                    request_deserializer=daemon__pb2.PacketQ.FromString,
                    response_serializer=daemon__pb2.PacketA.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recc.proto.DaemonApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DaemonApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Packet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recc.proto.DaemonApi/Packet',
            daemon__pb2.PacketQ.SerializeToString,
            daemon__pb2.PacketA.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pickling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recc.proto.DaemonApi/Pickling',
            daemon__pb2.PacketQ.SerializeToString,
            daemon__pb2.PacketA.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
