#!/usr/bin/env bash

function run_install
{
    exit 0
}

function run_upgrade
{
    exit 0
}

case "$1" in
install)
    run_install
    ;;
upgrade)
    run_upgrade
    ;;
*)
    echo "Unrecognized preinst argument '$1'"
esac
