#!/usr/bin/env bash

function run_remove
{
    exit 0
}

function run_upgrade
{
    exit 0
}

case "$1" in
remove)
    run_remove
    ;;
upgrade)
    run_upgrade
    ;;
*)
    echo "Unrecognized prerm argument '$1'"
esac
