version: '3.8'

services:
  community_postgres:
    container_name: community-answer-pg
    image: timescale/timescaledb:2.1.0-pg13
    restart: always
    volumes:
      - community_postgres_data:/var/lib/postgresql/data
    labels:
      - com.bogonets.answer.cluster=true
      - com.bogonets.answer.cluster.category=db
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=${POSTGRES_USER:-recc}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-recc1234}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-recc}"]
      interval: 10s
      timeout: 5s
      retries: 5

  community_minio:
    container_name: community-answer-minio
    image: minio/minio:RELEASE.2020-12-18T03-27-42Z
    restart: always
    volumes:
      - community_minio_data:/data
    labels:
      - com.bogonets.answer.cluster=true
      - com.bogonets.answer.cluster.category=s3
    environment:
      - TZ=Asia/Seoul
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-recc}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-recc1234}
    command: ["server", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-XGET", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  community_redis:
    container_name: community-answer-redis
    image: redis:6
    restart: always
    volumes:
      - community_redis_data:/data
    labels:
      - com.bogonets.answer.cluster=true
      - com.bogonets.answer.cluster.category=cache
    environment:
      - TZ=Asia/Seoul
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  community_recc:
    container_name: community-answer-recc
    image: bogonets/recc:latest
    restart: always
    volumes:
      - community_recc_data:/recc
    ports:
      - 20000:20000
    labels:
      - com.bogonets.answer.cluster=true
      - com.bogonets.answer.cluster.category=server
    environment:
      - TZ=Asia/Seoul
      - RECC_DATABASE_HOST=community_postgres
      - RECC_DATABASE_PORT=5432
      - RECC_DATABASE_USER=${POSTGRES_USER:-recc}
      - RECC_DATABASE_PW=${POSTGRES_PASSWORD:-recc1234}
      - RECC_CACHE_HOST=community_redis
      - RECC_CACHE_PORT=6379
      - RECC_STORAGE_HOST=community_minio
      - RECC_STORAGE_PORT=9000
      - RECC_STORAGE_USER=${MINIO_ACCESS_KEY:-recc}
      - RECC_STORAGE_PW=${MINIO_SECRET_KEY:-recc1234}
    healthcheck:
      test: ["CMD", "curl", "-XGET", "-f", "http://localhost:20000/api/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  community_postgres_data:
  community_minio_data:
  community_redis_data:
  community_recc_data:
