version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:2.1.0-pg13
    restart: always
    volumes:
      - recc_dev_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=${POSTGRES_USER:-recc}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-recc1234}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-recc}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2020-12-18T03-27-42Z
    restart: always
    volumes:
      - recc_dev_minio_data:/data
    ports:
      - 9000:9000
    environment:
      - TZ=Asia/Seoul
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-recc}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-recc1234}
    command: ["server", "/data"]
    healthcheck:
      test: ["CMD", "curl", "-XGET", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    restart: always
    volumes:
      - recc_dev_redis_data:/data
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  recc_dev_postgres_data:
  recc_dev_minio_data:
  recc_dev_redis_data:
