"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RegisterCode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RegisterCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RegisterCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Success: _RegisterCode.ValueType  # 0
    NotFoundRegisterFunction: _RegisterCode.ValueType  # 1
class RegisterCode(_RegisterCode, metaclass=_RegisterCodeEnumTypeWrapper):
    pass

Success: RegisterCode.ValueType  # 0
NotFoundRegisterFunction: RegisterCode.ValueType  # 1
global___RegisterCode = RegisterCode


class _Coding:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _CodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Coding.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Raw: _Coding.ValueType  # 0
    Pickle5: _Coding.ValueType  # 1
    Json: _Coding.ValueType  # 2
    """Automatically select the installed json library."""

    JsonZlib: _Coding.ValueType  # 3
    JsonGzip: _Coding.ValueType  # 4
    JsonLzma: _Coding.ValueType  # 5
    JsonBz2: _Coding.ValueType  # 6
    Pyjson: _Coding.ValueType  # 7
    """System default json library."""

    PyjsonZlib: _Coding.ValueType  # 8
    PyjsonGzip: _Coding.ValueType  # 9
    PyjsonLzma: _Coding.ValueType  # 10
    PyjsonBz2: _Coding.ValueType  # 11
    Orjson: _Coding.ValueType  # 12
    """orjson module"""

    OrjsonZlib: _Coding.ValueType  # 13
    OrjsonGzip: _Coding.ValueType  # 14
    OrjsonLzma: _Coding.ValueType  # 15
    OrjsonBz2: _Coding.ValueType  # 16
    Msgpack: _Coding.ValueType  # 17
    """msgpack module"""

    MsgpackZlib: _Coding.ValueType  # 18
    MsgpackGzip: _Coding.ValueType  # 19
    MsgpackLzma: _Coding.ValueType  # 20
    MsgpackBz2: _Coding.ValueType  # 21
    Yaml: _Coding.ValueType  # 22
    """yaml module"""

    YamlZlib: _Coding.ValueType  # 23
    YamlGzip: _Coding.ValueType  # 24
    YamlLzma: _Coding.ValueType  # 25
    YamlBz2: _Coding.ValueType  # 26
class Coding(_Coding, metaclass=_CodingEnumTypeWrapper):
    pass

Raw: Coding.ValueType  # 0
Pickle5: Coding.ValueType  # 1
Json: Coding.ValueType  # 2
"""Automatically select the installed json library."""

JsonZlib: Coding.ValueType  # 3
JsonGzip: Coding.ValueType  # 4
JsonLzma: Coding.ValueType  # 5
JsonBz2: Coding.ValueType  # 6
Pyjson: Coding.ValueType  # 7
"""System default json library."""

PyjsonZlib: Coding.ValueType  # 8
PyjsonGzip: Coding.ValueType  # 9
PyjsonLzma: Coding.ValueType  # 10
PyjsonBz2: Coding.ValueType  # 11
Orjson: Coding.ValueType  # 12
"""orjson module"""

OrjsonZlib: Coding.ValueType  # 13
OrjsonGzip: Coding.ValueType  # 14
OrjsonLzma: Coding.ValueType  # 15
OrjsonBz2: Coding.ValueType  # 16
Msgpack: Coding.ValueType  # 17
"""msgpack module"""

MsgpackZlib: Coding.ValueType  # 18
MsgpackGzip: Coding.ValueType  # 19
MsgpackLzma: Coding.ValueType  # 20
MsgpackBz2: Coding.ValueType  # 21
Yaml: Coding.ValueType  # 22
"""yaml module"""

YamlZlib: Coding.ValueType  # 23
YamlGzip: Coding.ValueType  # 24
YamlLzma: Coding.ValueType  # 25
YamlBz2: Coding.ValueType  # 26
global___Coding = Coding


class Pit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DELAY_FIELD_NUMBER: builtins.int
    delay: builtins.float
    def __init__(self,
        *,
        delay: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["delay",b"delay"]) -> None: ...
global___Pit = Pit

class Pat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(self,
        *,
        ok: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ok",b"ok"]) -> None: ...
global___Pat = Pat

class RegisterQ(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class KwargsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        value: typing.Text
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    SESSION_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    KWARGS_FIELD_NUMBER: builtins.int
    TEST_SM_NAME_FIELD_NUMBER: builtins.int
    TEST_SM_PASS_FIELD_NUMBER: builtins.int
    session: typing.Text
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def kwargs(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    test_sm_name: typing.Text
    test_sm_pass: typing.Text
    def __init__(self,
        *,
        session: typing.Text = ...,
        args: typing.Optional[typing.Iterable[typing.Text]] = ...,
        kwargs: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        test_sm_name: typing.Text = ...,
        test_sm_pass: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","kwargs",b"kwargs","session",b"session","test_sm_name",b"test_sm_name","test_sm_pass",b"test_sm_pass"]) -> None: ...
global___RegisterQ = RegisterQ

class RegisterA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    IS_SM_FIELD_NUMBER: builtins.int
    MIN_SM_SIZE_FIELD_NUMBER: builtins.int
    MIN_SM_BYTE_FIELD_NUMBER: builtins.int
    code: global___RegisterCode.ValueType
    is_sm: builtins.bool
    min_sm_size: builtins.int
    min_sm_byte: builtins.int
    def __init__(self,
        *,
        code: global___RegisterCode.ValueType = ...,
        is_sm: builtins.bool = ...,
        min_sm_size: builtins.int = ...,
        min_sm_byte: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","is_sm",b"is_sm","min_sm_byte",b"min_sm_byte","min_sm_size",b"min_sm_size"]) -> None: ...
global___RegisterA = RegisterA

class ArrayInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHAPE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    STRIDES_FIELD_NUMBER: builtins.int
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    dtype: typing.Text
    @property
    def strides(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        shape: typing.Optional[typing.Iterable[builtins.int]] = ...,
        dtype: typing.Text = ...,
        strides: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dtype",b"dtype","shape",b"shape","strides",b"strides"]) -> None: ...
global___ArrayInfo = ArrayInfo

class Content(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SIZE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    SM_NAME_FIELD_NUMBER: builtins.int
    ARRAY_FIELD_NUMBER: builtins.int
    size: builtins.int
    data: builtins.bytes
    sm_name: typing.Text
    @property
    def array(self) -> global___ArrayInfo: ...
    def __init__(self,
        *,
        size: builtins.int = ...,
        data: builtins.bytes = ...,
        sm_name: typing.Optional[typing.Text] = ...,
        array: typing.Optional[global___ArrayInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_array",b"_array","_sm_name",b"_sm_name","array",b"array","sm_name",b"sm_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_array",b"_array","_sm_name",b"_sm_name","array",b"array","data",b"data","size",b"size","sm_name",b"sm_name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_array",b"_array"]) -> typing.Optional[typing_extensions.Literal["array"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_sm_name",b"_sm_name"]) -> typing.Optional[typing_extensions.Literal["sm_name"]]: ...
global___Content = Content

class PacketQ(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class KwargsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___Content: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___Content] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    SESSION_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    CODING_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    KWARGS_FIELD_NUMBER: builtins.int
    SM_NAMES_FIELD_NUMBER: builtins.int
    session: typing.Text
    method: typing.Text
    path: typing.Text
    coding: global___Coding.ValueType
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Content]: ...
    @property
    def kwargs(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___Content]: ...
    @property
    def sm_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        session: typing.Text = ...,
        method: typing.Text = ...,
        path: typing.Text = ...,
        coding: global___Coding.ValueType = ...,
        args: typing.Optional[typing.Iterable[global___Content]] = ...,
        kwargs: typing.Optional[typing.Mapping[typing.Text, global___Content]] = ...,
        sm_names: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","coding",b"coding","kwargs",b"kwargs","method",b"method","path",b"path","session",b"session","sm_names",b"sm_names"]) -> None: ...
global___PacketQ = PacketQ

class PacketA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class KwargsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___Content: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___Content] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ARGS_FIELD_NUMBER: builtins.int
    KWARGS_FIELD_NUMBER: builtins.int
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Content]: ...
    @property
    def kwargs(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___Content]: ...
    def __init__(self,
        *,
        args: typing.Optional[typing.Iterable[global___Content]] = ...,
        kwargs: typing.Optional[typing.Mapping[typing.Text, global___Content]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","kwargs",b"kwargs"]) -> None: ...
global___PacketA = PacketA
