"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _ContentType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ContentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    Pickle5: ContentType.ValueType = ...  # 0
    Json: ContentType.ValueType = ...  # 1
    JsonZlib: ContentType.ValueType = ...  # 2
    JsonGzip: ContentType.ValueType = ...  # 3
    JsonLzma: ContentType.ValueType = ...  # 4
    JsonBz2: ContentType.ValueType = ...  # 5
    Msgpack: ContentType.ValueType = ...  # 6
    MsgpackZlib: ContentType.ValueType = ...  # 7
    MsgpackGzip: ContentType.ValueType = ...  # 8
    MsgpackLzma: ContentType.ValueType = ...  # 9
    MsgpackBz2: ContentType.ValueType = ...  # 10
class ContentType(_ContentType, metaclass=_ContentTypeEnumTypeWrapper):
    pass

Pickle5: ContentType.ValueType = ...  # 0
Json: ContentType.ValueType = ...  # 1
JsonZlib: ContentType.ValueType = ...  # 2
JsonGzip: ContentType.ValueType = ...  # 3
JsonLzma: ContentType.ValueType = ...  # 4
JsonBz2: ContentType.ValueType = ...  # 5
Msgpack: ContentType.ValueType = ...  # 6
MsgpackZlib: ContentType.ValueType = ...  # 7
MsgpackGzip: ContentType.ValueType = ...  # 8
MsgpackLzma: ContentType.ValueType = ...  # 9
MsgpackBz2: ContentType.ValueType = ...  # 10
global___ContentType = ContentType


class Pit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DELAY_FIELD_NUMBER: builtins.int
    delay: builtins.float = ...
    def __init__(self,
        *,
        delay : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["delay",b"delay"]) -> None: ...
global___Pit = Pit

class Pat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool = ...
    def __init__(self,
        *,
        ok : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ok",b"ok"]) -> None: ...
global___Pat = Pat

class InitQ(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class KwargsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    class ConfigsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    ARGS_FIELD_NUMBER: builtins.int
    KWARGS_FIELD_NUMBER: builtins.int
    CONFIGS_FIELD_NUMBER: builtins.int
    TEST_SM_NAME_FIELD_NUMBER: builtins.int
    TEST_SM_PASS_FIELD_NUMBER: builtins.int
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def kwargs(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    @property
    def configs(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    test_sm_name: typing.Text = ...
    test_sm_pass: typing.Text = ...
    def __init__(self,
        *,
        args : typing.Optional[typing.Iterable[typing.Text]] = ...,
        kwargs : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        configs : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        test_sm_name : typing.Text = ...,
        test_sm_pass : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","configs",b"configs","kwargs",b"kwargs","test_sm_name",b"test_sm_name","test_sm_pass",b"test_sm_pass"]) -> None: ...
global___InitQ = InitQ

class InitA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CODE_FIELD_NUMBER: builtins.int
    IS_SM_FIELD_NUMBER: builtins.int
    code: builtins.int = ...
    is_sm: builtins.bool = ...
    def __init__(self,
        *,
        code : builtins.int = ...,
        is_sm : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","is_sm",b"is_sm"]) -> None: ...
global___InitA = InitA

class PacketQ(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    METHOD_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    SM_NAME_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    CONTENT_SIZE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    method: typing.Text = ...
    path: typing.Text = ...
    sm_name: typing.Text = ...
    content_type: global___ContentType.ValueType = ...
    content_size: builtins.int = ...
    content: builtins.bytes = ...
    def __init__(self,
        *,
        method : typing.Text = ...,
        path : typing.Text = ...,
        sm_name : typing.Text = ...,
        content_type : global___ContentType.ValueType = ...,
        content_size : builtins.int = ...,
        content : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_content",b"_content","content",b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_content",b"_content","content",b"content","content_size",b"content_size","content_type",b"content_type","method",b"method","path",b"path","sm_name",b"sm_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_content",b"_content"]) -> typing.Optional[typing_extensions.Literal["content"]]: ...
global___PacketQ = PacketQ

class PacketA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONTENT_SIZE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    content_size: builtins.int = ...
    content: builtins.bytes = ...
    def __init__(self,
        *,
        content_size : builtins.int = ...,
        content : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_content",b"_content","content",b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_content",b"_content","content",b"content","content_size",b"content_size"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_content",b"_content"]) -> typing.Optional[typing_extensions.Literal["content"]]: ...
global___PacketA = PacketA
