# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daemon_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daemon_api.proto',
  package='recc.proto.daemon',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61\x65mon_api.proto\x12\x11recc.proto.daemon\"\x14\n\x03Pit\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x02\"\x11\n\x03Pat\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x8e\x02\n\x05InitQ\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\x12\x34\n\x06kwargs\x18\x02 \x03(\x0b\x32$.recc.proto.daemon.InitQ.KwargsEntry\x12\x36\n\x07\x63onfigs\x18\x03 \x03(\x0b\x32%.recc.proto.daemon.InitQ.ConfigsEntry\x12\x14\n\x0ctest_sm_name\x18\x04 \x01(\t\x12\x14\n\x0ctest_sm_pass\x18\x05 \x01(\t\x1a-\n\x0bKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"$\n\x05InitA\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05is_sm\x18\x02 \x01(\x08\"\xa6\x01\n\x07PacketQ\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07sm_name\x18\x03 \x01(\t\x12\x34\n\x0c\x63ontent_type\x18\x04 \x01(\x0e\x32\x1e.recc.proto.daemon.ContentType\x12\x14\n\x0c\x63ontent_size\x18\x05 \x01(\x05\x12\x14\n\x07\x63ontent\x18\x06 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_content\"A\n\x07PacketA\x12\x14\n\x0c\x63ontent_size\x18\x01 \x01(\x05\x12\x14\n\x07\x63ontent\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_content*\xab\x01\n\x0b\x43ontentType\x12\x0b\n\x07Pickle5\x10\x00\x12\x08\n\x04Json\x10\x01\x12\x0c\n\x08JsonZlib\x10\x02\x12\x0c\n\x08JsonGzip\x10\x03\x12\x0c\n\x08JsonLzma\x10\x04\x12\x0b\n\x07JsonBz2\x10\x05\x12\x0b\n\x07Msgpack\x10\x06\x12\x0f\n\x0bMsgpackZlib\x10\x07\x12\x0f\n\x0bMsgpackGzip\x10\x08\x12\x0f\n\x0bMsgpackLzma\x10\t\x12\x0e\n\nMsgpackBz2\x10\n2\xcc\x01\n\tDaemonApi\x12=\n\tHeartbeat\x12\x16.recc.proto.daemon.Pit\x1a\x16.recc.proto.daemon.Pat\"\x00\x12<\n\x04Init\x12\x18.recc.proto.daemon.InitQ\x1a\x18.recc.proto.daemon.InitA\"\x00\x12\x42\n\x06Packet\x12\x1a.recc.proto.daemon.PacketQ\x1a\x1a.recc.proto.daemon.PacketA\"\x00\x62\x06proto3'
)

_CONTENTTYPE = _descriptor.EnumDescriptor(
  name='ContentType',
  full_name='recc.proto.daemon.ContentType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Pickle5', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Json', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JsonZlib', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JsonGzip', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JsonLzma', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JsonBz2', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Msgpack', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MsgpackZlib', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MsgpackGzip', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MsgpackLzma', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MsgpackBz2', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=628,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_CONTENTTYPE)

ContentType = enum_type_wrapper.EnumTypeWrapper(_CONTENTTYPE)
Pickle5 = 0
Json = 1
JsonZlib = 2
JsonGzip = 3
JsonLzma = 4
JsonBz2 = 5
Msgpack = 6
MsgpackZlib = 7
MsgpackGzip = 8
MsgpackLzma = 9
MsgpackBz2 = 10



_PIT = _descriptor.Descriptor(
  name='Pit',
  full_name='recc.proto.daemon.Pit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delay', full_name='recc.proto.daemon.Pit.delay', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=59,
)


_PAT = _descriptor.Descriptor(
  name='Pat',
  full_name='recc.proto.daemon.Pat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='recc.proto.daemon.Pat.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=78,
)


_INITQ_KWARGSENTRY = _descriptor.Descriptor(
  name='KwargsEntry',
  full_name='recc.proto.daemon.InitQ.KwargsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='recc.proto.daemon.InitQ.KwargsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='recc.proto.daemon.InitQ.KwargsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=303,
)

_INITQ_CONFIGSENTRY = _descriptor.Descriptor(
  name='ConfigsEntry',
  full_name='recc.proto.daemon.InitQ.ConfigsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='recc.proto.daemon.InitQ.ConfigsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='recc.proto.daemon.InitQ.ConfigsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=351,
)

_INITQ = _descriptor.Descriptor(
  name='InitQ',
  full_name='recc.proto.daemon.InitQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='recc.proto.daemon.InitQ.args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='recc.proto.daemon.InitQ.kwargs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configs', full_name='recc.proto.daemon.InitQ.configs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_sm_name', full_name='recc.proto.daemon.InitQ.test_sm_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_sm_pass', full_name='recc.proto.daemon.InitQ.test_sm_pass', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INITQ_KWARGSENTRY, _INITQ_CONFIGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=351,
)


_INITA = _descriptor.Descriptor(
  name='InitA',
  full_name='recc.proto.daemon.InitA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='recc.proto.daemon.InitA.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_sm', full_name='recc.proto.daemon.InitA.is_sm', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=389,
)


_PACKETQ = _descriptor.Descriptor(
  name='PacketQ',
  full_name='recc.proto.daemon.PacketQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='recc.proto.daemon.PacketQ.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='recc.proto.daemon.PacketQ.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sm_name', full_name='recc.proto.daemon.PacketQ.sm_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_type', full_name='recc.proto.daemon.PacketQ.content_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_size', full_name='recc.proto.daemon.PacketQ.content_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='recc.proto.daemon.PacketQ.content', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='recc.proto.daemon.PacketQ._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=392,
  serialized_end=558,
)


_PACKETA = _descriptor.Descriptor(
  name='PacketA',
  full_name='recc.proto.daemon.PacketA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_size', full_name='recc.proto.daemon.PacketA.content_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='recc.proto.daemon.PacketA.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='recc.proto.daemon.PacketA._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=560,
  serialized_end=625,
)

_INITQ_KWARGSENTRY.containing_type = _INITQ
_INITQ_CONFIGSENTRY.containing_type = _INITQ
_INITQ.fields_by_name['kwargs'].message_type = _INITQ_KWARGSENTRY
_INITQ.fields_by_name['configs'].message_type = _INITQ_CONFIGSENTRY
_PACKETQ.fields_by_name['content_type'].enum_type = _CONTENTTYPE
_PACKETQ.oneofs_by_name['_content'].fields.append(
  _PACKETQ.fields_by_name['content'])
_PACKETQ.fields_by_name['content'].containing_oneof = _PACKETQ.oneofs_by_name['_content']
_PACKETA.oneofs_by_name['_content'].fields.append(
  _PACKETA.fields_by_name['content'])
_PACKETA.fields_by_name['content'].containing_oneof = _PACKETA.oneofs_by_name['_content']
DESCRIPTOR.message_types_by_name['Pit'] = _PIT
DESCRIPTOR.message_types_by_name['Pat'] = _PAT
DESCRIPTOR.message_types_by_name['InitQ'] = _INITQ
DESCRIPTOR.message_types_by_name['InitA'] = _INITA
DESCRIPTOR.message_types_by_name['PacketQ'] = _PACKETQ
DESCRIPTOR.message_types_by_name['PacketA'] = _PACKETA
DESCRIPTOR.enum_types_by_name['ContentType'] = _CONTENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pit = _reflection.GeneratedProtocolMessageType('Pit', (_message.Message,), {
  'DESCRIPTOR' : _PIT,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.Pit)
  })
_sym_db.RegisterMessage(Pit)

Pat = _reflection.GeneratedProtocolMessageType('Pat', (_message.Message,), {
  'DESCRIPTOR' : _PAT,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.Pat)
  })
_sym_db.RegisterMessage(Pat)

InitQ = _reflection.GeneratedProtocolMessageType('InitQ', (_message.Message,), {

  'KwargsEntry' : _reflection.GeneratedProtocolMessageType('KwargsEntry', (_message.Message,), {
    'DESCRIPTOR' : _INITQ_KWARGSENTRY,
    '__module__' : 'daemon_api_pb2'
    # @@protoc_insertion_point(class_scope:recc.proto.daemon.InitQ.KwargsEntry)
    })
  ,

  'ConfigsEntry' : _reflection.GeneratedProtocolMessageType('ConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _INITQ_CONFIGSENTRY,
    '__module__' : 'daemon_api_pb2'
    # @@protoc_insertion_point(class_scope:recc.proto.daemon.InitQ.ConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _INITQ,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.InitQ)
  })
_sym_db.RegisterMessage(InitQ)
_sym_db.RegisterMessage(InitQ.KwargsEntry)
_sym_db.RegisterMessage(InitQ.ConfigsEntry)

InitA = _reflection.GeneratedProtocolMessageType('InitA', (_message.Message,), {
  'DESCRIPTOR' : _INITA,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.InitA)
  })
_sym_db.RegisterMessage(InitA)

PacketQ = _reflection.GeneratedProtocolMessageType('PacketQ', (_message.Message,), {
  'DESCRIPTOR' : _PACKETQ,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.PacketQ)
  })
_sym_db.RegisterMessage(PacketQ)

PacketA = _reflection.GeneratedProtocolMessageType('PacketA', (_message.Message,), {
  'DESCRIPTOR' : _PACKETA,
  '__module__' : 'daemon_api_pb2'
  # @@protoc_insertion_point(class_scope:recc.proto.daemon.PacketA)
  })
_sym_db.RegisterMessage(PacketA)


_INITQ_KWARGSENTRY._options = None
_INITQ_CONFIGSENTRY._options = None

_DAEMONAPI = _descriptor.ServiceDescriptor(
  name='DaemonApi',
  full_name='recc.proto.daemon.DaemonApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=802,
  serialized_end=1006,
  methods=[
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='recc.proto.daemon.DaemonApi.Heartbeat',
    index=0,
    containing_service=None,
    input_type=_PIT,
    output_type=_PAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='recc.proto.daemon.DaemonApi.Init',
    index=1,
    containing_service=None,
    input_type=_INITQ,
    output_type=_INITA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Packet',
    full_name='recc.proto.daemon.DaemonApi.Packet',
    index=2,
    containing_service=None,
    input_type=_PACKETQ,
    output_type=_PACKETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAEMONAPI)

DESCRIPTOR.services_by_name['DaemonApi'] = _DAEMONAPI

# @@protoc_insertion_point(module_scope)
