# -*- coding: utf-8 -*-

WELL_KNOWN_PORT_MIN = 0
WELL_KNOWN_PORT_MAX = 1023
WELL_KNOWN_PORT_RANGE = (WELL_KNOWN_PORT_MIN, WELL_KNOWN_PORT_MAX)

REGISTERED_PORT_MIN = 1024
REGISTERED_PORT_MAX = 49151
REGISTERED_PORT_RANGE = (REGISTERED_PORT_MIN, REGISTERED_PORT_MAX)

DYNAMIC_PORT_MIN = 49152
DYNAMIC_PORT_MAX = 65535
DYNAMIC_PORT_RANGE = (DYNAMIC_PORT_MIN, DYNAMIC_PORT_MAX)

DEFAULT_RECC_CORE_PORT = 20000
DEFAULT_RECC_NODE_PORT_MIN = 20010
DEFAULT_RECC_NODE_PORT_MAX = REGISTERED_PORT_MAX
DEFAULT_RECC_NODE_PORT_RANGE = (DEFAULT_RECC_NODE_PORT_MIN, DEFAULT_RECC_NODE_PORT_MAX)
