export const Names = {
    errorNotFound: 'ErrorNotFound',
    mainAbout: 'MainAbout',
    mainAccountAppearance: 'MainAccountAppearance',
    mainAccount: 'MainAccount',

    adminInfos: 'AdminInfos.vue',
    adminConfigs: 'AdminConfigs.vue',
    adminGroups: 'AdminGroups.vue',
    adminGroupsNew: 'AdminGroupsNew.vue',
    adminGroupsEdit: 'AdminGroupsEdit.vue',
    adminLamdas: 'AdminTemplates.vue',
    adminOverview: 'AdminOverview.vue',
    adminPermissions: 'AdminPermissions.vue',
    adminPermissionsNew: 'AdminPermissionsNew.vue',
    adminPermissionsEdit: 'AdminPermissionsEdit.vue',
    adminProjects: 'AdminProjects.vue',
    adminProjectsNew: 'AdminProjectsNew.vue',
    adminProjectsEdit: 'AdminProjectsEdit.vue',
    adminTasks: 'AdminTasks.vue',
    adminUsersEdit: 'AdminUsersEdit.vue',
    adminUsersNew: 'AdminUsersNew.vue',
    adminUsers: 'AdminUsers.vue',
    admin: 'Admin.vue',

    mainDashboard: 'MainDashboard',
    mainDevTools: 'MainDevTools',
    mainGroups: 'MainGroups',
    mainGroupsNew: 'MainGroupsNew',
    mainProjectConfigs: 'MainProjectConfigs',
    mainProjectMembers: 'MainProjectMembers',
    mainProjectAirjoyTables: 'MainProjectAirjoyTables',
    mainProjectAirjoyStatistics: 'MainProjectAirjoyStatistics',
    mainProjectAirjoyMonitoring: 'MainProjectAirjoyMonitoring',
    mainProjectDashboard: 'MainProjectDashboard',
    mainProjectFiles: 'MainProjectFiles',
    mainProjectLayouts: 'MainProjectLayouts',
    mainProjectsNew: 'MainProjectsNew',
    mainProjects: 'MainProjects',
    mainProjectTables: 'MainProjectTables',
    mainProjectTasks: 'MainProjectTasks',
    mainProjectVisualProgramming: 'MainProjectVisualProgramming',
    mainProjectVms: 'MainProjectVms',
    mainProject: 'MainProject',
    main: 'Main',
    signin: 'Signin',
    signup: 'Signup',
    signupAdmin: 'SignupAdmin',
};

export default Names;
