export const Names = {
    errorNotFound: 'ErrorNotFound',
    about: 'About',

    admin: 'RouterBarMainNaviAdmin',
    adminConfigs: 'AdminConfigs',
    adminGroups: 'AdminGroups',
    adminGroupsEdit: 'AdminGroupsEdit',
    adminGroupsNew: 'AdminGroupsNew',
    adminInfos: 'AdminInfos',
    adminOverview: 'AdminOverview',
    adminPermissions: 'AdminPermissions',
    adminPermissionsEdit: 'AdminPermissionsEdit',
    adminPermissionsNew: 'AdminPermissionsNew',
    adminProjects: 'AdminProjects',
    adminProjectsEdit: 'AdminProjectsEdit',
    adminProjectsNew: 'AdminProjectsNew',
    adminTasks: 'AdminTasks',
    adminTemplates: 'AdminTemplates',
    adminUsers: 'AdminUsers',
    adminUsersEdit: 'AdminUsersEdit',
    adminUsersNew: 'AdminUsersNew',
    dev: 'RouterBarMainNaviDev',

    // REFACTORING BEGIN ---
    mainDashboard: 'MainDashboard',
    mainProjectConfigs: 'MainProjectConfigs',
    mainProjectMembers: 'MainProjectMembers',
    mainProjectAirjoyTables: 'MainProjectAirjoyTables',
    mainProjectAirjoyStatistics: 'MainProjectAirjoyStatistics',
    mainProjectAirjoyMonitoring: 'MainProjectAirjoyMonitoring',
    mainProjectDashboard: 'MainProjectDashboard',
    mainProjectFiles: 'MainProjectFiles',
    mainProjectLayouts: 'MainProjectLayouts',
    mainProjectsNew: 'MainProjectsNew',
    mainProjects: 'MainProjects',
    mainProjectTables: 'MainProjectTables',
    mainProjectTasks: 'MainProjectTasks',
    mainProjectVisualProgramming: 'MainProjectVisualProgramming',
    mainProjectVms: 'MainProjectVms',
    mainProject: 'MainProject',
    // END ---

    main: 'RouterBarMain',
    mainOverview: 'MainOverview',
    mainGroup: 'RouterNaviGroup',
    mainGroupMembers: 'MainGroupMembers',
    mainGroupProjects: 'MainGroupProjects',
    mainGroupSettings: 'mainGroupSettings',
    mainGroups: 'MainGroups',
    mainGroupsNew: 'MainGroupsNew',

    self: 'RouterBarMainNaviSelf',
    selfAppearance: 'SelfAppearance',

    signin: 'Signin',
    signup: 'Signup',
    init: 'SignupAdmin',
};

export default Names;
