# -*- coding: utf-8 -*-

from recc.database.query.create.functions.appropriate_permission import (
    CREATE_FUNC_APPROPRIATE_PERMISSION,
    DROP_FUNC_APPROPRIATE_PERMISSION,
)

CREATE_FUNCTIONS = (CREATE_FUNC_APPROPRIATE_PERMISSION,)
DROP_FUNCTIONS = (DROP_FUNC_APPROPRIATE_PERMISSION,)

__all__ = ("CREATE_FUNCTIONS", "DROP_FUNCTIONS")
