# -*- coding: utf-8 -*-

CS_TYPE_NAME_REDIS = "redis"

DEFAULT_MAX_CONNECTIONS = 10

CACHE_PREFIX_ROOT = "/recc"
CACHE_PREFIX_USER = CACHE_PREFIX_ROOT + "/user"
CACHE_PREFIX_GROUP = CACHE_PREFIX_ROOT + "/group"
CACHE_PREFIX_PROJECT = CACHE_PREFIX_ROOT + "/project"
CACHE_PREFIX_PERMISSION = CACHE_PREFIX_ROOT + "/permission"

# fmt: off
CACHE_FORMAT_USER_NAME_TO_UID = CACHE_PREFIX_USER + "/name_to_uid/{name}"
CACHE_FORMAT_USER_UID_TO_NAME = CACHE_PREFIX_USER + "/uid_to_name/{uid}"

CACHE_FORMAT_GROUP_SLUG_TO_UID = CACHE_PREFIX_GROUP + "/slug_to_uid/{slug}"
CACHE_FORMAT_GROUP_UID_TO_SLUG = CACHE_PREFIX_GROUP + "/uid_to_slug/{uid}"

CACHE_FORMAT_PROJECT_KEY_TO_UID = CACHE_PREFIX_PROJECT + "/key_to_uid/{key}"
CACHE_FORMAT_PROJECT_UID_TO_KEY = CACHE_PREFIX_PROJECT + "/uid_to_key/{uid}"

CACHE_FORMAT_PERMISSION_SLUG_TO_UID = CACHE_PREFIX_PERMISSION + "/slug_to_uid/{slug}"
CACHE_FORMAT_PERMISSION_UID_TO_SLUG = CACHE_PREFIX_PERMISSION + "/uid_to_slug/{uid}"
# fmt: on

PROJECT_KEY_SEPARATOR = "/"
PROJECT_KEY_FORMAT = "{group_uid}" + PROJECT_KEY_SEPARATOR + "{project_slug}"
