# -*- coding: utf-8 -*-

CONTAINER_TYPE_DOCKER = "docker"
CONTAINER_TYPE_SWARM = "swarm"
CONTAINER_TYPE_KUBERNETES = "kubernetes"

DOCKER_SOCK_LOCAL_BASE_URL = "unix://var/run/docker.sock"

BASE_IMAGE_NAME = "python"
BASE_IMAGE_TAG = "3.8.9"
BASE_IMAGE_FULLNAME = f"{BASE_IMAGE_NAME}:{BASE_IMAGE_TAG}"

NODE_IMAGE_NAME = "recc-task-image"
NODE_IMAGE_LATEST_FULLNAME = f"{NODE_IMAGE_NAME}:latest"

DEFAULT_RESTART_COUNT = 5
DEFAULT_TIME_ZONE = "Asia/Seoul"
