# -*- coding: utf-8 -*-

from recc.variables.port import DEFAULT_CORE_HTTP_PORT, TEST_CORE_HTTP_PORT

DEFAULT_HTTP_BIND = "0.0.0.0"
DEFAULT_HTTP_PORT = DEFAULT_CORE_HTTP_PORT
DEFAULT_HTTP_ADDRESS = f"{DEFAULT_HTTP_BIND}:{DEFAULT_HTTP_PORT}"
DEFAULT_HTTP_TEST_PORT = TEST_CORE_HTTP_PORT
DEFAULT_HTTP_TIMEOUT = 5 * 60.0
DEFAULT_SCHEME = "http"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30.0
DEFAULT_CLIENT_MAX_SIZE = 100 * 1024 * 1024

URI_AUTHORITY_SUFFIX = "@"
URI_PATH_SEPARATOR = "/"
URI_QUERY_PREFIX = "?"
URI_FRAGMENT_PREFIX = "#"

XML_ROOT_TAG = "data"

DEBUGGING_BODY_MSG_MAX_SIZE = 1024
VERY_VERBOSE_DEBUGGING = 2
