# -*- coding: utf-8 -*-

from recc.variables.port import DEFAULT_CORE_HTTP_PORT, TEST_CORE_HTTP_PORT

DEFAULT_HTTP_BIND = "0.0.0.0"
DEFAULT_HTTP_PORT = DEFAULT_CORE_HTTP_PORT
DEFAULT_HTTP_TEST_PORT = TEST_CORE_HTTP_PORT
DEFAULT_HTTP_TIMEOUT = 5 * 60.0
DEFAULT_SCHEME = "http"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30.0

URL_PATH_SEPARATOR = "/"

XML_ROOT_TAG = "data"

DETAIL_RESPONSE_LOGGING_VERBOSE_LEVEL = 2
