# -*- coding: utf-8 -*-

RECC_CLUSTER_KEY = "recc.cluster"
RECC_CLUSTER_VAL_TRUE = "true"
RECC_CLUSTER_VAL_FALSE = "false"
RECC_CLUSTER_TRUE = f"{RECC_CLUSTER_KEY}={RECC_CLUSTER_VAL_TRUE}"
RECC_CLUSTER_FALSE = f"{RECC_CLUSTER_KEY}={RECC_CLUSTER_VAL_FALSE}"

RECC_CATEGORY_KEY = "recc.category"
RECC_CATEGORY_VAL_TASK = "task"
RECC_CATEGORY_VAL_IMAGE = "image"
RECC_CATEGORY_TASK = f"{RECC_CATEGORY_KEY}={RECC_CATEGORY_VAL_TASK}"
RECC_CATEGORY_IMAGE = f"{RECC_CATEGORY_KEY}={RECC_CATEGORY_VAL_IMAGE}"

RECC_IMAGE_VERSION_KEY = "recc.image.version"
RECC_IMAGE_SHA256_KEY = "recc.image.sha256"

RECC_TASK_GROUP_KEY = "recc.task.group"
RECC_TASK_PROJECT_KEY = "recc.task.project"
RECC_TASK_TASK_KEY = "recc.task.task"
