# -*- coding: utf-8 -*-

ANSWER_CLUSTER_KEY = "answer.cluster"
ANSWER_CLUSTER_VAL_TRUE = "true"
ANSWER_CLUSTER_VAL_FALSE = "false"

ANSWER_CLUSTER_TRUE = f"{ANSWER_CLUSTER_KEY}={ANSWER_CLUSTER_VAL_TRUE}"
ANSWER_CLUSTER_FALSE = f"{ANSWER_CLUSTER_KEY}={ANSWER_CLUSTER_VAL_FALSE}"

assert ANSWER_CLUSTER_TRUE == "answer.cluster=true"
assert ANSWER_CLUSTER_FALSE == "answer.cluster=false"

ANSWER_CLUSTER_CATEGORY_KEY = "answer.cluster.category"
ANSWER_CLUSTER_CATEGORY_VAL_NODE = "node"

_CATEGORY = ANSWER_CLUSTER_CATEGORY_KEY
_CATEGORY_NODE = ANSWER_CLUSTER_CATEGORY_VAL_NODE
ANSWER_CLUSTER_CATEGORY_NODE = f"{_CATEGORY}={_CATEGORY_NODE}"

assert ANSWER_CLUSTER_CATEGORY_NODE == "answer.cluster.category=node"

ANSWER_CLUSTER_NODE_GROUP_KEY = "answer.cluster.node.group"
ANSWER_CLUSTER_NODE_PROJECT_KEY = "answer.cluster.node.project"
ANSWER_CLUSTER_NODE_TASK_KEY = "answer.cluster.node.task"

ANSWER_CLUSTER_KEYS = (
    ANSWER_CLUSTER_KEY,
    ANSWER_CLUSTER_CATEGORY_KEY,
    ANSWER_CLUSTER_NODE_GROUP_KEY,
    ANSWER_CLUSTER_NODE_PROJECT_KEY,
    ANSWER_CLUSTER_NODE_TASK_KEY,
)
