# -*- coding: utf-8 -*-

CM_TYPE_NAME_DOCKER = "docker"
CM_TYPE_NAME_SWARM = "swarm"
CM_TYPE_NAME_KUBERNETES = "kubernetes"

DOCKER_SOCK_LOCAL_BASE_URL = "unix://var/run/docker.sock"

BASE_IMAGE_NAME = "python"
BASE_IMAGE_TAG = "3.8.9"
BASE_IMAGE_FULLNAME = f"{BASE_IMAGE_NAME}:{BASE_IMAGE_TAG}"

NODE_IMAGE_NAME = "osom8979/recc-node"
NODE_IMAGE_TAG = f"{BASE_IMAGE_NAME}-{BASE_IMAGE_TAG}"
NODE_IMAGE_FULLNAME = f"{NODE_IMAGE_NAME}:{NODE_IMAGE_TAG}"
NODE_IMAGE_LATEST_FULLNAME = f"{NODE_IMAGE_NAME}:latest"

DEFAULT_RESTART_COUNT = 5
DEFAULT_TIME_ZONE = "Asia/Seoul"
