# -*- coding: utf-8 -*-

WELL_KNOWN_PORT_MIN = 0
WELL_KNOWN_PORT_MAX = 1023
WELL_KNOWN_PORT_RANGE = (WELL_KNOWN_PORT_MIN, WELL_KNOWN_PORT_MAX)

REGISTERED_PORT_MIN = 1024
REGISTERED_PORT_MAX = 49151
REGISTERED_PORT_RANGE = (REGISTERED_PORT_MIN, REGISTERED_PORT_MAX)

DYNAMIC_PORT_MIN = 49152
DYNAMIC_PORT_MAX = 65535
DYNAMIC_PORT_RANGE = (DYNAMIC_PORT_MIN, DYNAMIC_PORT_MAX)

# [WARNING] Port number 30000 conflicts with KakaoTalk.
DEFAULT_MANAGEABLE_MINIMUM_PORT_NUMBER = 30001
DEFAULT_MANAGEABLE_MAXIMUM_PORT_NUMBER = REGISTERED_PORT_MAX

DEFAULT_CORE_HTTP_PORT = 20000
DEFAULT_TASK_RPC_PORT = DEFAULT_MANAGEABLE_MINIMUM_PORT_NUMBER

TEST_CORE_HTTP_PORT = 29999
