# -*- coding: utf-8 -*-

from datetime import datetime
from typing import Optional
from recc.chrono.datetime import today
from recc.variables.database import (
    TABLE_PERMISSION,
    PERMISSION_SLUG_RECC_LAYOUT_READ,
    PERMISSION_SLUG_RECC_LAYOUT_WRITE,
    PERMISSION_SLUG_RECC_STORAGE_READ,
    PERMISSION_SLUG_RECC_STORAGE_WRITE,
    PERMISSION_SLUG_RECC_MANAGER_READ,
    PERMISSION_SLUG_RECC_MANAGER_WRITE,
    PERMISSION_SLUG_RECC_GRAPH_READ,
    PERMISSION_SLUG_RECC_GRAPH_WRITE,
    PERMISSION_SLUG_RECC_MEMBER_READ,
    PERMISSION_SLUG_RECC_MEMBER_WRITE,
    PERMISSION_SLUG_RECC_SETTING_READ,
    PERMISSION_SLUG_RECC_SETTING_WRITE,
)

INITIALIZE_ONLY_INSERT_PERMISSION_FORMAT = f"""
INSERT INTO {TABLE_PERMISSION} (
    slug,
    created_at
) SELECT
    '{{slug}}',
    '{{created_at}}'
WHERE
    NOT EXISTS(
        SELECT uid
        FROM {TABLE_PERMISSION}
        WHERE slug='{{slug}}'
    );
"""


def get_safe_insert_permission_query(
    slug: str,
    created_at: Optional[datetime] = None,
) -> str:
    created = created_at if created_at else today()
    return INITIALIZE_ONLY_INSERT_PERMISSION_FORMAT.format(
        slug=slug,
        created_at=created,
    )


# fmt: off
INSERT_PERMISSION_RECC_LAYOUT_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_LAYOUT_READ)  # noqa
INSERT_PERMISSION_RECC_LAYOUT_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_LAYOUT_WRITE)  # noqa
INSERT_PERMISSION_RECC_STORAGE_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_STORAGE_READ)  # noqa
INSERT_PERMISSION_RECC_STORAGE_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_STORAGE_WRITE)  # noqa
INSERT_PERMISSION_RECC_MANAGER_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_MANAGER_READ)  # noqa
INSERT_PERMISSION_RECC_MANAGER_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_MANAGER_WRITE)  # noqa
INSERT_PERMISSION_RECC_GRAPH_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_GRAPH_READ)  # noqa
INSERT_PERMISSION_RECC_GRAPH_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_GRAPH_WRITE)  # noqa
INSERT_PERMISSION_RECC_MEMBER_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_MEMBER_READ)  # noqa
INSERT_PERMISSION_RECC_MEMBER_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_MEMBER_WRITE)  # noqa
INSERT_PERMISSION_RECC_SETTING_READ = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_SETTING_READ)  # noqa
INSERT_PERMISSION_RECC_SETTING_WRITE = get_safe_insert_permission_query(PERMISSION_SLUG_RECC_SETTING_WRITE)  # noqa
# fmt: on

INSERT_PERMISSION_DEFAULTS = (
    INSERT_PERMISSION_RECC_LAYOUT_READ,
    INSERT_PERMISSION_RECC_LAYOUT_WRITE,
    INSERT_PERMISSION_RECC_STORAGE_READ,
    INSERT_PERMISSION_RECC_STORAGE_WRITE,
    INSERT_PERMISSION_RECC_MANAGER_READ,
    INSERT_PERMISSION_RECC_MANAGER_WRITE,
    INSERT_PERMISSION_RECC_GRAPH_READ,
    INSERT_PERMISSION_RECC_GRAPH_WRITE,
    INSERT_PERMISSION_RECC_MEMBER_READ,
    INSERT_PERMISSION_RECC_MEMBER_WRITE,
    INSERT_PERMISSION_RECC_SETTING_READ,
    INSERT_PERMISSION_RECC_SETTING_WRITE,
)

INSERT_PERMISSION = f"""
INSERT INTO {TABLE_PERMISSION} (
    slug,
    created_at
) VALUES (
    $1,
    $2
) RETURNING uid;
"""

DELETE_PERMISSION_BY_UID = f"""
DELETE FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_UID_BY_SLUG = f"""
SELECT uid
FROM {TABLE_PERMISSION}
WHERE slug=$1;
"""

SELECT_PERMISSION_SLUG_BY_UID = f"""
SELECT slug
FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_BY_SLUG = f"""
SELECT *
FROM {TABLE_PERMISSION}
WHERE slug=$1;
"""

SELECT_PERMISSION_BY_UID = f"""
SELECT *
FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_ALL = f"""
SELECT *
FROM {TABLE_PERMISSION};
"""
