# -*- coding: utf-8 -*-

from recc.variables.database import (
    TABLE_PERMISSION,
    TABLE_ROLE_PERMISSION,
    FUNC_APPROPRIATE_PERMISSION,
    DEFAULT_PERMISSION_SLUGS,
)

INSERT_PERMISSION = f"""
INSERT INTO {TABLE_PERMISSION} (
    slug,
    created_at
) VALUES (
    $1,
    $2
) RETURNING uid;
"""

DELETE_PERMISSION_BY_UID = f"""
DELETE FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_UID_BY_SLUG = f"""
SELECT uid
FROM {TABLE_PERMISSION}
WHERE slug=$1;
"""

SELECT_PERMISSION_SLUG_BY_UID = f"""
SELECT slug
FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_BY_SLUG = f"""
SELECT *
FROM {TABLE_PERMISSION}
WHERE slug=$1;
"""

SELECT_PERMISSION_BY_UID = f"""
SELECT *
FROM {TABLE_PERMISSION}
WHERE uid=$1;
"""

SELECT_PERMISSION_ALL = f"""
SELECT *
FROM {TABLE_PERMISSION};
"""

SELECT_PERMISSION_BY_ROLE_UID = f"""
SELECT *
FROM {TABLE_PERMISSION}
WHERE uid IN (
    SELECT permission_uid
    FROM {TABLE_ROLE_PERMISSION}
    WHERE role_uid=$1
);
"""

SELECT_APPROPRIATE_PERMISSION_BY_USER_AND_GROUP = f"""
SELECT * FROM {FUNC_APPROPRIATE_PERMISSION}($1, $2);
"""

SELECT_APPROPRIATE_PERMISSION_BY_USER_AND_GROUP_AND_PROJECT = f"""
SELECT * FROM {FUNC_APPROPRIATE_PERMISSION}($1, $2, $3);
"""

_INSERT_PERMISSION_ONLY_SLUG_FORMAT = f"""
INSERT INTO {TABLE_PERMISSION} (
    slug,
    created_at
) VALUES (
    '{{slug}}',
    NOW()
);
"""


def _insert_permission_only_slug(slug: str) -> str:
    return _INSERT_PERMISSION_ONLY_SLUG_FORMAT.format(slug=slug)


INSERT_PERMISSION_DEFAULTS = list(
    map(lambda x: _insert_permission_only_slug(x), DEFAULT_PERMISSION_SLUGS)
)
