# -*- coding: utf-8 -*-

from recc.variables.database import (
    TABLE_INFO,
    TABLE_USER,
    TABLE_GROUP_MEMBER,
    TABLE_PROJECT_MEMBER,
    VIEW_INFO_DB_VERSION,
    VIEW_USER_ADMIN,
    VIEW_USER_ADMIN_COUNT,
    VIEW_UNION_MEMBER,
    INFO_KEY_RECC_DB_VERSION,
    UNION_MEMBER_CATEGORY_GROUP,
    UNION_MEMBER_CATEGORY_PROJECT,
)

CREATE_VIEW_INFO_DB_VERSION = f"""
CREATE OR REPLACE VIEW {VIEW_INFO_DB_VERSION}
AS SELECT
    value AS version
FROM
    {TABLE_INFO}
WHERE
    key='{INFO_KEY_RECC_DB_VERSION}';
"""

CREATE_VIEW_USER_ADMIN = f"""
CREATE OR REPLACE VIEW {VIEW_USER_ADMIN}
AS SELECT
    uid, username, email
FROM
    {TABLE_USER}
WHERE
    is_admin=TRUE;
"""

CREATE_VIEW_USER_ADMIN_COUNT = f"""
CREATE OR REPLACE VIEW {VIEW_USER_ADMIN_COUNT}
AS SELECT
    count(uid) AS count
FROM
    {TABLE_USER}
WHERE
    is_admin=TRUE;
"""

CREATE_VIEW_UNION_MEMBER = f"""
CREATE OR REPLACE VIEW {VIEW_UNION_MEMBER}
AS SELECT
    group_uid AS domain_uid,
    user_uid,
    role_uid,
    {UNION_MEMBER_CATEGORY_GROUP} AS category
FROM {TABLE_GROUP_MEMBER}
UNION ALL
SELECT
    project_uid AS domain_uid,
    user_uid,
    role_uid,
    {UNION_MEMBER_CATEGORY_PROJECT} AS category
FROM {TABLE_PROJECT_MEMBER};
"""

CREATE_VIEWS = (
    CREATE_VIEW_INFO_DB_VERSION,
    CREATE_VIEW_USER_ADMIN,
    CREATE_VIEW_USER_ADMIN_COUNT,
    CREATE_VIEW_UNION_MEMBER,
)

DROP_VIEW_INFO_VERSION = f"DROP VIEW IF EXISTS {VIEW_INFO_DB_VERSION};"
DROP_VIEW_USER_ADMIN = f"DROP VIEW IF EXISTS {VIEW_USER_ADMIN};"
DROP_VIEW_USER_ADMIN_COUNT = f"DROP VIEW IF EXISTS {VIEW_USER_ADMIN_COUNT};"
DROP_VIEW_UNION_MEMBER = f"DROP VIEW IF EXISTS {VIEW_UNION_MEMBER};"

DROP_VIEWS = (
    DROP_VIEW_INFO_VERSION,
    DROP_VIEW_USER_ADMIN,
    DROP_VIEW_USER_ADMIN_COUNT,
    DROP_VIEW_UNION_MEMBER,
)
